config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "u", path_names: { sign_in: 'login', sign_out: 'logout', confirmation: 'verification', sign_up: 'register' }
  match "choose_customer", controller: "home", action: "choose_customer", via: [:get]
  match "select_active_customer", controller: "home", action: "select_active_customer", via: [:get]
  match "customer_selected", controller: "home", action: "customer_selected", via: [:post]
  match "clear_customer", controller: "home", action:"clear_customer", via: [:get]
  match "super_admin_choose_customer", controller: "home", action: "super_admin_choose_customer", via: [:get]
  namespace :super_admin do
    resources :customers
  end
  resources :customers do
    resources :mappings
    resources :phone_numbers
  end
  devise_scope :user do
    match "sign_in", to: "devise/sessions#new", via: [:get]
  end

  namespace :json, path: 'json' do
    resources :customers do
      resources :mappings
      resources :phone_numbers
    end
    resources :mappings do
      resources :phone_numbers
    end
    match 'get_applied_numbers', controller: "json_director", action: "get_applied_numbers", via: [:get]
  end
  root to: 'home#index'

  post 'messager', to: 'messager#incoming'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # this is the default site landing page
  end
  def choose_customer
    @customers = current_user.customers
    if @customers.count.zero?
      if current_user.user_type.name == "super_admin"
        redirect_to super_admin_choose_customer_path
      else
        redirect_to select_active_customer_path
      end
    elsif @customers.count < 2
      # Go to the only customer's mapping page
      current_customer = @customers.first
      session[:current_customer] = current_customer
      redirect_to customer_mappings_path(current_customer)
    else
      # If there is more than one customer, go to a choose_customer page
      redirect_to select_active_customer_path
    end
  end

  def select_active_customer
    @customers = current_user.customers
  end

  def customer_selected
    params.inspect
    session[:current_customer] = Customer.find(params[:chosen_customer])
    redirect_to customer_mappings_path(session[:current_customer])
  end
  def clear_customer
    session[:current_customer] = nil
    redirect_to select_active_customer_path
  end

  def super_admin_choose_customer
    if current_user.user_type.name == "super_admin"
      @customers = Customer.all
    else
      redirect_to select_active_customer_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_home_tabs.html.haml
%li.disabled
  = link_to root_path, title: "No Customer Chosen" do
    = fa_icon "male"
    %span.hidden-xs.hidden-sm= "No Customer Chosen"

%li{class: (active_tab == 'general') ? 'active' : nil}
  = link_to root_path(anchor: 'general'), title: 'Dashboard', data: {toggle: 'tab'} do
    = fa_icon "tachometer"
    %span.hidden-xs.hidden-sm Dashboard

- if true #can?(:index, Subscription)
  %li{class: (active_tab == 'subscriptions') ? 'active' : nil}
    = link_to root_path, title: 'Subscriptions' do
      = fa_icon 'repeat'
      %span.hidden-xs.hidden-sm Subscriptions

- if true #can?(:index, Contract)
  %li{class: (active_tab == 'contracts') ? 'active' : nil}
    = link_to root_path, title: 'My Agreement' do
      = fa_icon 'gavel'
      %span.hidden-xs.hidden-sm My Agreement

- if true #can?(:index, CreditCard)
  %li{class: (active_tab == 'credit_cards') ? 'active' : nil}
    = link_to root_path, title: 'Credit Cards' do
      = fa_icon 'credit-card'
      %span.hidden-xs.hidden-sm Credit Cards

- if true #can?(:index, Document)
  %li{class: (active_tab == 'documents') ? 'active' : nil}
    = link_to root_path, title: 'Documents' do
      = fa_icon "folder-o"
      %span.hidden-xs.hidden-sm Documents

%li{class: (active_tab == 'tickets') ? 'active' : nil}
  = link_to root_path, title: 'Tickets' do
    = fa_icon "fire-extinguisher"
    %span.hidden-xs.hidden-sm Support

app/views/home/index.html.haml
%h1 This is the main site landing page.

%h3 
  Please click
  =link_to 'here', new_user_session_path
  to log in.

app/views/home/select_active_customer.html.haml
- title "Choose Customer", true, {fa_icon: 'tachometer'}

- content_for(:sidebar) do
  = render 'home_tabs', active_tab: 'general'
- if @customers.empty?
  %ul
    %li You don't have any customers assigned. Contact your account rep to gain access to a customer account.
- else
  %ul
    - @customers.each do |customer|
      %li= link_to customer.business_name, customer_selected_path(chosen_customer: customer), method: :post

app/views/home/super_admin_choose_customer.html.haml
- title "Choose Customer", true, {fa_icon: 'tachometer'}

- content_for(:sidebar) do
  = render 'home_tabs', active_tab: 'general'
- if @customers.empty?
  %ul
    %li You don't have any customers assigned. Contact your account rep to gain access to a customer account.
- else
  %ul
    - @customers.each do |customer|
      %li= link_to customer.business_name, customer_selected_path(chosen_customer: customer), method: :post