config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "u", path_names: { sign_in: 'login', sign_out: 'logout', confirmation: 'verification', sign_up: 'register' }
  match "choose_customer", controller: "home", action: "choose_customer", via: [:get]
  match "select_active_customer", controller: "home", action: "select_active_customer", via: [:get]
  match "customer_selected", controller: "home", action: "customer_selected", via: [:post]
  match "clear_customer", controller: "home", action:"clear_customer", via: [:get]
  match "super_admin_choose_customer", controller: "home", action: "super_admin_choose_customer", via: [:get]
  namespace :super_admin do
    resources :customers
  end
  resources :customers do
    resources :mappings
    resources :phone_numbers
  end
  devise_scope :user do
    match "sign_in", to: "devise/sessions#new", via: [:get]
  end

  namespace :json, path: 'json' do
    resources :customers do
      resources :mappings
      resources :phone_numbers
    end
    resources :mappings do
      resources :phone_numbers
    end
    match 'get_applied_numbers', controller: "json_director", action: "get_applied_numbers", via: [:get]
  end
  root to: 'home#index'

  post 'messager', to: 'messager#incoming'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :phone_numbers
  has_many :mappings
  has_many :customers_users
  has_many :users, through: :customers_users

  before_save :create_uuid

  def create_uuid
    if self.uuid.blank?
      self.uuid = SecureRandom.uuid
    end
  end

  def get_mapping_from_message(message)
    self.mappings.find_by(received_text: message).reply_text
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:business_name, :stripe_id, :uuid)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :business_name %><br>
    <%= f.text_field :business_name %>
  </div>
  <div class="field">
    <%= f.label :stripe_id %><br>
    <%= f.text_field :stripe_id %>
  </div>
  <div class="field">
    <%= f.label :uuid %><br>
    <%= f.text_field :uuid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>Business name</th>
      <th>Stripe</th>
      <th>Uuid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.business_name %></td>
        <td><%= customer.stripe_id %></td>
        <td><%= customer.uuid %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Business name:</strong>
  <%= @customer.business_name %>
</p>

<p>
  <strong>Stripe:</strong>
  <%= @customer.stripe_id %>
</p>

<p>
  <strong>Uuid:</strong>
  <%= @customer.uuid %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>