config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "u", path_names: { sign_in: 'login', sign_out: 'logout', confirmation: 'verification', sign_up: 'register' }
  match "choose_customer", controller: "home", action: "choose_customer", via: [:get]
  match "select_active_customer", controller: "home", action: "select_active_customer", via: [:get]
  match "customer_selected", controller: "home", action: "customer_selected", via: [:post]
  match "clear_customer", controller: "home", action:"clear_customer", via: [:get]
  match "super_admin_choose_customer", controller: "home", action: "super_admin_choose_customer", via: [:get]
  namespace :super_admin do
    resources :customers
  end
  resources :customers do
    resources :mappings
    resources :phone_numbers
  end
  devise_scope :user do
    match "sign_in", to: "devise/sessions#new", via: [:get]
  end

  namespace :json, path: 'json' do
    resources :customers do
      resources :mappings
      resources :phone_numbers
    end
    resources :mappings do
      resources :phone_numbers
    end
    match 'get_applied_numbers', controller: "json_director", action: "get_applied_numbers", via: [:get]
  end
  root to: 'home#index'

  post 'messager', to: 'messager#incoming'
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  belongs_to :customer
  has_many :mapped_phones
  has_many :mappings, through: :mapped_phones

  before_create :add_plus1
  before_update :add_plus1

  def add_plus1
    # we need to add +1 to the beginning of the phone number. 
    unless self.number.include?("+1")
      self.number = "+1" + self.number
    end
  end
end

app/controllers/json/phone_numbers_controller.rb
module Json
  class PhoneNumbersController < JsonDirectorController
    #phone numbers controller
    before_action :set_mapping
    # load_and_authorize_resource :mapping
    # load_and_authorize_resource :phone_numbers, through: :mapped_phones

    respond_to :js
    def index
      # will return the applied numbers for a mapping
      @applied_numbers = MappedPhone.where(mapping: @mapping)

      sleep 1 #development only, simulates wait time
      respond_to do |format|
        format.html { redirect_to root_path } #for my controller, i wanted it to be JS only
        format.js
      end
    end

    private
    def set_mapping
      # This will set the mapping to the correct instance. 
      @mapping = Mapping.find(params[:mapping_id])
    end
  end
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :set_phone_number, only: [:show, :edit, :update, :destroy]
  before_action :current_customer
  # GET /phone_numbers
  # GET /phone_numbers.json
  def index
    @phone_numbers = current_customer.phone_numbers
    # @phone_numbers = PhoneNumber.all
  end

  # GET /phone_numbers/1
  # GET /phone_numbers/1.json
  def show
  end

  # GET /phone_numbers/new
  def new
    @phone_number = PhoneNumber.new
  end

  # GET /phone_numbers/1/edit
  def edit
  end

  # POST /phone_numbers
  # POST /phone_numbers.json
  def create
    @phone_number = PhoneNumber.new(phone_number_params)

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number, notice: 'Phone number was successfully created.' }
        format.json { render :show, status: :created, location: @phone_number }
      else
        format.html { render :new }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_numbers/1
  # PATCH/PUT /phone_numbers/1.json
  def update
    respond_to do |format|
      if @phone_number.update(phone_number_params)
        format.html { redirect_to customer_phone_number_path(session[:current_customer]["id"], @phone_number), notice: 'Phone number was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_number }
      else
        format.html { render :edit }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_numbers/1
  # DELETE /phone_numbers/1.json
  def destroy
    @phone_number.destroy
    respond_to do |format|
      format.html { redirect_to customer_phone_numbers_url(session[:current_customer]["id"]), notice: 'Phone number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_number
      @phone_number = PhoneNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_number_params
      params.require(:phone_number).permit(:number, :ours, :customer_id, :our_metadata, :customer_metadata)
    end

    def current_customer
      Customer.find(params[:customer_id])
    end
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/phone_numbers/_form.html.haml
= form_for([current_customer, @phone_number]) do |f|
  - if @phone_number.errors.any?
    .error_explanation
      %h2= "#{pluralize(@phone_number.errors.count, 'error')} prohibited this phone_number from being saved:"
      %ul
        - @phone_number.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :number
    %br
    = f.text_field :number
  .field
    = f.label :ours 
    %br
    = f.check_box :ours
  .field
    = f.label :customer_id
    %br
    = f.text_field :customer_id
  .field
    = f.label :our_metadata 
    %br
    = f.text_area :our_metadata
  .field
    = f.label :customer_metadata 
    %br
    = f.text_area :customer_metadata
  .actions
    = f.submit

app/views/phone_numbers/edit.html.haml
%h1 Editing Phone Number

= render 'form'

= link_to 'Show', customer_phone_number_path(current_customer, @phone_number) |
= link_to 'Back', customer_phone_numbers_path(current_customer)

app/views/phone_numbers/index.html.haml
- title "My Dashboard", true, {fa_icon: 'tachometer'}

- content_for(:sidebar) do
  = render 'mappings/partials/mapping_tabs', active_tab: 'general'

.p{:id => "notice"}= notice

%h1 Listing Phone Numbers

%table
  %thead
    %tr
      %th Number
      %th Ours
      %th Customer
      %th Our metadata
      %th Customer metadata
      %th{:colspan => "3"}

  %tbody
    - @phone_numbers.each do |phone_number|
      %tr
        %td= phone_number.number
        %td= phone_number.ours
        %td= phone_number.customer.nil? ? "Not assigned" : phone_number.customer.business_name
        %td= phone_number.our_metadata
        %td= phone_number.customer_metadata
        %td= link_to 'Show', customer_phone_number_path(current_customer, phone_number)
        %td= link_to 'Edit', edit_customer_phone_number_path(current_customer, phone_number)
        %td= link_to 'Destroy', customer_phone_number_path(current_customer, phone_number), method: :delete, data: { confirm: 'Are you sure?' }
%br

= link_to 'New Phone number', new_customer_phone_number_path(current_customer)

app/views/phone_numbers/new.html.haml
%h1 New Phone Number

= render 'form'

= link_to 'Back', phone_numbers_path

app/views/phone_numbers/show.html.haml
%p#notice= notice

%p
  %strong Number:
  = @phone_number.number

%p
  %strong Ours:
  = @phone_number.ours

%p
  %strong Customer:
  = @phone_number.customer

%p
  %strong Our metadata:
  = @phone_number.our_metadata

%p
  %strong Customer metadata:
  = @phone_number.customer_metadata 

= link_to 'Edit', edit_customer_phone_number_path(current_customer, @phone_number) |
= link_to 'Back', customer_phone_numbers_path(current_customer)