config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "u", path_names: { sign_in: 'login', sign_out: 'logout', confirmation: 'verification', sign_up: 'register' }
  match "choose_customer", controller: "home", action: "choose_customer", via: [:get]
  match "select_active_customer", controller: "home", action: "select_active_customer", via: [:get]
  match "customer_selected", controller: "home", action: "customer_selected", via: [:post]
  match "clear_customer", controller: "home", action:"clear_customer", via: [:get]
  match "super_admin_choose_customer", controller: "home", action: "super_admin_choose_customer", via: [:get]
  namespace :super_admin do
    resources :customers
  end
  resources :customers do
    resources :mappings
    resources :phone_numbers
  end
  devise_scope :user do
    match "sign_in", to: "devise/sessions#new", via: [:get]
  end

  namespace :json, path: 'json' do
    resources :customers do
      resources :mappings
      resources :phone_numbers
    end
    resources :mappings do
      resources :phone_numbers
    end
    match 'get_applied_numbers', controller: "json_director", action: "get_applied_numbers", via: [:get]
  end
  root to: 'home#index'

  post 'messager', to: 'messager#incoming'
end

app/models/mapping.rb
class Mapping < ActiveRecord::Base
  belongs_to :customer
  belongs_to :mapping_type
  has_many :mapped_phones
  has_many :phone_numbers, through: :mapped_phones
end

app/models/mapping_type.rb
class MappingType < ActiveRecord::Base
  has_one :mapping
end

app/controllers/mappings_controller.rb
class MappingsController < ApplicationController
  before_action :set_mapping, only: [:show, :edit, :update, :destroy]
  before_action :set_current_customer
  # load_and_authorize_resource :customer
  current_customer = Customer.new

  # GET /mappings
  # GET /mappings.json
  def index
    # @mappings = Mapping.all
    current_customer = set_current_customer
    @mappings = current_customer.mappings
  end

  # GET /mappings/1
  # GET /mappings/1.json
  def show
  end

  # GET /mappings/new
  def new
    @mapping = Mapping.new
  end

  # GET /mappings/1/edit
  def edit
  end

  # POST /mappings
  # POST /mappings.json
  def create
    @mapping = Mapping.new(mapping_params)

    respond_to do |format|
      if @mapping.save
        format.html { redirect_to @mapping, notice: 'Mapping was successfully created.' }
        format.json { render :show, status: :created, location: @mapping }
      else
        format.html { render :new }
        format.json { render json: @mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mappings/1
  # PATCH/PUT /mappings/1.json
  def update
    respond_to do |format|
      if @mapping.update(mapping_params)
        format.html { redirect_to @mapping, notice: 'Mapping was successfully updated.' }
        format.json { render :show, status: :ok, location: @mapping }
      else
        format.html { render :edit }
        format.json { render json: @mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mappings/1
  # DELETE /mappings/1.json
  def destroy
    @mapping.destroy
    respond_to do |format|
      format.html { redirect_to mappings_url, notice: 'Mapping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mapping
      @mapping = Mapping.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mapping_params
      params.require(:mapping).permit(:customer_id, :phone_number_id, :incoming_phone_number_id, :received_text, :reply_text, :current_customer)
    end

    def set_current_customer
      current_customer = Customer.find(session[:current_customer]["id"])
    end
end

app/helpers/mappings_helper.rb
module MappingsHelper
end

app/views/mappings/_form.html.haml
= form_for(@mapping) do |f|
  - if @mapping.errors.any? 
    .error_explanation
      %h2= pluralize(@mapping.errors.count, 'error') "prohibited this mapping from being saved:"
      %ul
        - @mapping.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :customer_id 
    %br
    = f.text_field :customer_id 
  .field
    = f.label ':phone_number_id '
    %br
    / = f.text_field ':phone_number_id'
  .field
    = f.label ':incoming_phone_number_id'
    %br
    / = f.text_field ':incoming_phone_number_id '
  .field
    = f.label :received_text 
    %br
    = f.text_field :received_text
  .field
    = f.label :reply_text 
    %br
    = f.text_field :reply_text
  .actions
    = f.submit

app/views/mappings/edit.html.haml
- title "My Dashboard", true, {fa_icon: 'tachometer'}

- content_for(:sidebar) do
  = render 'mappings/partials/mapping_tabs', active_tab: 'general'

%h1 Editing Mapping

= render 'form'

= link_to 'Show', @mapping |
= link_to 'Back', mappings_path

app/views/mappings/index.html.haml
- title "My Dashboard", true, {fa_icon: 'tachometer'}

- content_for(:sidebar) do
  = render 'mappings/partials/mapping_tabs', active_tab: 'general'

.tab-content
  .tab-pane.active#general
    .panel.panel-default
      .panel-heading
        %h4 Mappings
      .panel-body
        .table-responsive
          %table.table.table-striped.table-hover.table-condensed
            %tbody
              %tr
                %th= "Incoming Number"
                %th= "Received Text"
                %th= "Reply Text"
                %th= "Mapping Type"
                %th= "Edit"
                %th= "Delete"
              - @mappings.each do |mapping|
                %tr
                  / %td= link_to "Applied Numbers", json_get_applied_numbers_path({mapping_id: mapping.id}), remote: true, class: 'static-popup-link'
                  %td= link_to "Applied Numbers", json_mapping_phone_numbers_path(@mapping.id), class: 'btn btn-success', role: "button", data: {toggle: "modal", target: '#customerModal', remote: true}, title: "Mappings to Phone Numbers"
                  %td= mapping.received_text
                  %td= mapping.reply_text
                  %td= mapping.mapping_type.name
                  %td= link_to 'Edit', edit_customer_mapping_path(current_user.customers.first, mapping)
                  / TODO: Fix the following link... It's broken
                  %td= link_to 'Destroy', root_path, method: :delete, data: { confirm: 'Are you sure?' }
            %table.table.table-striped.table-hover.table-condensed
            %tbody
              %tr
                = link_to 'Add New Mapping', new_customer_mapping_path

.modal.fade#customerModal{tabindex: '-1'}
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &times;
        %h3.modal-title
      .modal-body
        %p

app/views/mappings/new.html.erb
<h1>New Mapping</h1>

<%= render 'form' %>

<%= link_to 'Back', mappings_path %>

app/views/mappings/oldindex.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mappings</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Phone number</th>
      <th>Incoming phone number</th>
      <th>Received text</th>
      <th>Reply text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mappings.each do |mapping| %>
      <tr>
        <td><%= mapping.customer %></td>
        <td><%= mapping.phone_number %></td>
        <td><%= mapping.incoming_phone_number %></td>
        <td><%= mapping.received_text %></td>
        <td><%= mapping.reply_text %></td>
        <td><%= link_to 'Show', mapping %></td>
        <td><%= link_to 'Edit', edit_mapping_path(mapping) %></td>
        <td><%= link_to 'Destroy', mapping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mapping', new_mapping_path %>

app/views/mappings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @mapping.customer %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @mapping.phone_number %>
</p>

<p>
  <strong>Incoming phone number:</strong>
  <%= @mapping.incoming_phone_number %>
</p>

<p>
  <strong>Received text:</strong>
  <%= @mapping.received_text %>
</p>

<p>
  <strong>Reply text:</strong>
  <%= @mapping.reply_text %>
</p>

<%= link_to 'Edit', edit_mapping_path(@mapping) %> |
<%= link_to 'Back', mappings_path %>